In [1]:
import numpy as np

def gauss(A):
    # Make a copy, so that we won't lose the originals.
    B = np.array(A, dtype=np.float_)
    n, _ = B.shape
    
    # For each row, we need to set the total times of calcuation.
    OPRT = {i:range(i) for i in range(n)}
    
    # iterate
    for row, cols in OPRT.items():
        
        count = row
        # Check zeros on the pivot positions
        if np.isclose(B[row,row], 0):
            
            # Sometimes, we need Permutation for the matrix.
            while np.isclose(B[row,row], 0):
                count += 1
                try:
                    B[row] = B[row] + B[count]
                    for col in cols:
                        B[row] = B[row] - B[row, col] * B[col]
                
                # If zeros below, the matrix is singular.
                except IndexError:
                    raise MatrixIsSingular
            
            # Divide rows by pivots
            B[row] = B[row] / B[row,row]


        else:
            # Otherwise, just implement row operations.
            for col in cols:
                B[row] = B[row] - B[row, col] * B[col]

            B[row] = B[row] / B[row,row]
     
    return B

class MatrixIsSingular(Exception): pass

In [2]:
# Example1: needs Permuation
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float_)

In [3]:
gauss(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [4]:
# Example2: a Singular Matrix
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [0, 0, 0, 0]
    ], dtype=np.float_)

In [5]:
gauss(A)

MatrixIsSingular: 

## Computation

In [6]:
# Diagonal matrix
A = np.array([[5, 0, 0],
              [0, 4, 0],
              [0, 0, 3]])

In [7]:
gauss(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# uppertriangular matrix
B = np.array([[5, 1, 2],
              [0, 4, 4],
              [0, 0, 3]])

In [9]:
gauss(B)

array([[1. , 0.2, 0.4],
       [0. , 1. , 1. ],
       [0. , 0. , 1. ]])

In [10]:
# lowertriangular matrix
C = np.array([[5, 0, 0],
              [5, 4, 0],
              [0, 4, 3]])

In [11]:
gauss(C)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# General Matrix
M = np.array([[2, 4, -2],
              [4, 9, -3],
              [-2, -3, 7]])

In [13]:
gauss(M)

array([[ 1.,  2., -1.],
       [ 0.,  1.,  1.],
       [ 0.,  0.,  1.]])

In [14]:
gauss(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Evaluation

In [15]:
## A Programming Task submitted from the course in Coursera(Mathematics for Machine Learning).

# For Row Zero, all we require is the first element is equal to 1.
# We'll divide the row by the value of A[0, 0].
# This will get us in trouble though if A[0, 0] equals 0, so first we'll test for that,
# and if this is true, we'll add one of the lower rows to the first one before the division.
# We'll repeat the test going down each lower row until we can do the division.
# There is no need to edit this function.
def fixRowZero(A) :
    if A[0,0] == 0 :
        A[0] = A[0] + A[1]
    if A[0,0] == 0 :
        A[0] = A[0] + A[2]
    if A[0,0] == 0 :
        A[0] = A[0] + A[3]
    if A[0,0] == 0 :
        raise MatrixIsSingular()
    A[0] = A[0] / A[0,0]
    return A

# First we'll set the sub-diagonal elements to zero, i.e. A[1,0].
# Next we want the diagonal element to be equal to one.
# We'll divide the row by the value of A[1, 1].
# Again, we need to test if this is zero.
# If so, we'll add a lower row and repeat setting the sub-diagonal elements to zero.
# There is no need to edit this function.
def fixRowOne(A) :
    A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        raise MatrixIsSingular()
    A[1] = A[1] / A[1,1]
    return A

# Follow the instructions inside the function at each comment.
def fixRowTwo(A) :
    # Insert code below to set the sub-diagonal elements of row two to zero (there are two of them).
    A[2] = A[2] - A[2,0] * A[0]
    A[2] = A[2] - A[2,1] * A[1]
    
    # Next we'll test that the diagonal element is not zero.
    if A[2,2] == 0 :
        # Insert code below that adds a lower row to row 2.
        A[2] = A[2] + A[3]
        
        # Now repeat your code which sets the sub-diagonal elements to zero.
        A[2] = A[2] - A[2,0] * A[0]
        A[2] = A[2] - A[2,1] * A[1]        
        
    if A[2,2] == 0 :
        raise MatrixIsSingular()
    # Finally set the diagonal element to one by dividing the whole row by that element.
    A[2] = A[2] / A[2,2]
    return A

# Follow the instructions inside the function at each comment.
def fixRowThree(A) :
    # Insert code below to set the sub-diagonal elements of row three to zero.
    A[3] = A[3] - A[3,0] * A[0]
    A[3] = A[3] - A[3,1] * A[1]
    A[3] = A[3] - A[3,2] * A[2]
    
    
    # Complete the if statement to test if the diagonal element is zero.
    if A[3,3] == 0:
        raise MatrixIsSingular()
    # Transform the row to set the diagonal element to one.
    A[3] = A[3] / A[3,3]
    return A

In [16]:
A = np.array([
        [1, 1, 0, 0],
        [1, 2, 1, 0],
        [0, 1, 2, 1],
        [0, 0, 1, 2]
    ], dtype=np.float_)

In [17]:
fixRowZero(A)

array([[1., 1., 0., 0.],
       [1., 2., 1., 0.],
       [0., 1., 2., 1.],
       [0., 0., 1., 2.]])

In [18]:
fixRowOne(A)

array([[1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 2., 1.],
       [0., 0., 1., 2.]])

In [19]:
fixRowTwo(A)

array([[1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 2.]])

In [20]:
fixRowThree(A)

array([[1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [21]:
# Compare with my solution

A = np.array([
        [1, 1, 0, 0],
        [1, 2, 1, 0],
        [0, 1, 2, 1],
        [0, 0, 1, 2]
    ], dtype=np.float_)

gauss(A)

array([[1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [22]:
# We get the same result!!